#!/bin/bash

if [ "$1" = "c" ]
then 
  git commit -m "$2"
elif [ "$1" = "s" ]
then
  git status
elif [ "$1" = "a" ]
then
  git add .
elif [ "$1" = "p" ]
then
  git add . && git commit -m "$2" && git push
elif [ "$1" = "h" ]
then 
  git push heroku main
else
  echo "nothing to run"
fi