#!/bin/bash

echo "runniing"
source settings.env
echo "value of NODE_PATH=$NODE_PATH"


if [ "$1" = "s" ]
then
  echo "skipping run"
else
  if [ "$1" = "d" ]
  then 
    nodemon server/index.js
  else
    node server
  fi

fi