#!/bin/bash

echo "runniing"
export NODE_PATH=$PWD
echo "value of NODE_PATH=$NODE_PATH"
source settings.env


if [ "$1" = "s" ]
then
  echo "skipping run"
else
  if [ "$1" = "d" ]
  then 
    nodemon server/index.js
  else
    node server
  fi

fi